digit_6: 6
digit_50: 50
digit_140: 140
digit_255: 255
HUNDRED_YEARS: 100
size_50: 50
size_80: 80
option_gender: ["male", "female", "other"]
prompt_gender: "Select gender"
page_10: 10
size_5MB: 5.megabytes
size_500x500: [500, 500]
